### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by KKiim** [KKiim/CSB_Albatross_2017#1]
- Dual View
- Wetterfilter und Regionsfilter kombinieren(AND)

**Comment by PMeschenmoser** [comment]
Fließender Übergang, check.

**Comment by PMeschenmoser** [comment]
- Dualview funktioniert größtenteils: ggf. kleinere Bugs fixen
-  Ein paar Präsentationsslides vorbereiten, Researchquestions, Datenquellen, Challenges, Future Work

**Comment by PMeschenmoser** [comment]
Komische Scrollleiste wenn man dialog öffnet
